apiVersion: external-secrets.io/v1beta1
kind: ClusterExternalSecret
metadata:
  name: ecr-pull-secret-ces
spec:
  externalSecretName: ecr-pull-es
  namespaceSelector:
    matchExpressions:
      - key: kubernetes.io/metadata.name
        operator: In
        values:
          - kube-rca
  refreshTime: 1h
  externalSecretSpec:
    refreshInterval: 1h
    secretStoreRef:
      name: parameter-store
      kind: ClusterSecretStore
    target:
      name: ecr-pull-secret          # 생성될 Secret 이름
      template:
        type: kubernetes.io/dockerconfigjson
        data:
          # 아래 data[].secretKey 와 매핑
          .dockerconfigjson: '{{ .dockerconfigjson }}'
    data:
      - secretKey: dockerconfigjson
        remoteRef:
          key: ecr-pull-secret
